export { default as Bg } from './Bg'
export { default as Books } from './Books'
export { default as HomeBackground } from './HomeBackground'
export { default as Programmer } from './Programmer'
export { default as Watch } from './Watch'